idf_component_register(
  SRCS
  "src/config_routes.c"
  "src/json_processor.c"
  "src/web_server.c"
  "src/web_server_util.c"
  INCLUDE_DIRS
  "include"
  PRIV_INCLUDE_DIRS
  "priv_include"
  REQUIRES
  esp_http_server
  storage
  PRIV_REQUIRES
  esp_wifi
  esp_event
  esp_netif
  cjson
  nvs_flash
  config
  logger)
